version: '2'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/codeserver
  redis:
    image: "redis:alpine"
  agent:
    build: ./agent
    volumes:
    - ./agent:/codeagent